[profile.dev]
opt-level = 1

[profile.release]
lto = true

[workspace]
members = [
    "src/dg",
    "src/dg_tests",
    "src/libdg_cuda",
    "src/libdg_go",
    "src/libdg_mcts",
    "src/libdg_predict",
    "src/libdg_utils"
]
